services:
  marketplace_database:
    image: postgres:16
    container_name: marketplace_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_DB: marketplace
    
    ports:
      - "5434:5432"
    
    volumes:
      - ./marketplace/server/db/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - marketplace_database_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace_user -d marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5

  notifications_database:
    image: postgres:16
    container_name: notifications_db
    
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: notifications_password
      POSTGRES_DB: notifications
    
    ports:
      - "5433:5432"
    
    volumes:
      - ./notifications/server/db/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - notifications_database_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifications_user -d notifications"]
      interval: 5s
      timeout: 5s
      retries: 5

  consul:
    image: hashicorp/consul:1.17
    container_name: consul

    restart: unless-stopped
    
    ports:
      - "8500:8500"
    
    command: "agent -dev -client=0.0.0.0"
  
  marketplace_primary_server:
    build:
      context: ./marketplace/server
      dockerfile: Dockerfile
    container_name: marketplace_primary_server
    
    restart: unless-stopped

    environment:
      GRPC_PORT: 50051
      IS_PRIMARY: "true"
      SECONDARY_ADDRESS: marketplace_secondary_server:50054
      DATABASE_HOST: marketplace_database
      DATABASE_PORT: 5432
      DATABASE_USER: marketplace_user
      DATABASE_PASSWORD: marketplace_password
      DATABASE_NAME: marketplace
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    
    ports:
      - "50051:50051"
    
    depends_on:
      marketplace_database:
        condition: service_healthy
      consul:
        condition: service_started
  
  marketplace_secondary_server:
    build:
      context: ./marketplace/server
      dockerfile: Dockerfile
    container_name: marketplace_secondary_server
    
    restart: unless-stopped

    environment:
      GRPC_PORT: 50054
      IS_PRIMARY: "false"
      SECONDARY_ADDRESS: marketplace_primary_server:50051
      DATABASE_HOST: marketplace_database
      DATABASE_PORT: 5432
      DATABASE_USER: marketplace_user
      DATABASE_PASSWORD: marketplace_password
      DATABASE_NAME: marketplace
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    
    ports:
      - "50054:50054"
    
    depends_on:
      marketplace_database:
        condition: service_healthy
      consul:
        condition: service_started
  
  marketplace_gateway:
    build:
      context: ./marketplace/gateway
      dockerfile: Dockerfile
    container_name: marketplace_gateway

    restart: unless-stopped

    environment:
      HTTP_PORT: 8001
      MARKETPLACE_HOST: marketplace_primary_server
      MARKETPLACE_PORT: 50051
    
    ports:
      - "8001:8001"
    
    depends_on:
      - marketplace_primary_server
  
  notifications_primary_server:
    build:
      context: ./notifications/server
      dockerfile: Dockerfile
    container_name: notifications_primary_server

    restart: unless-stopped

    environment:
      GRPC_PORT: 50052
      IS_PRIMARY: "true"
      SECONDARY_ADDRESS: notifications_secondary_server:50053
      DATABASE_HOST: notifications_database
      DATABASE_PORT: 5432
      DATABASE_USER: notifications_user
      DATABASE_PASSWORD: notifications_password
      DATABASE_NAME: notifications
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      SERVICE_NAME: notifications-service

    ports:
      - "50052:50052"
    
    depends_on:
      notifications_database:
        condition: service_healthy
      consul:
        condition: service_started
  
  notifications_primary_server:
    build:
      context: ./notifications/server
      dockerfile: Dockerfile
    container_name: notifications_secondary_server

    restart: unless-stopped

    environment:
      GRPC_PORT: 50053
      IS_PRIMARY: "true"
      SECONDARY_ADDRESS: notifications_primary_server:50052
      DATABASE_HOST: notifications_database
      DATABASE_PORT: 5432
      DATABASE_USER: notifications_user
      DATABASE_PASSWORD: notifications_password
      DATABASE_NAME: notifications
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      SERVICE_NAME: notifications-service

    ports:
      - "50053:50053"
    
    depends_on:
      notifications_database:
        condition: service_healthy
      consul:
        condition: service_started
  
  notifications_gateway:
    build:
      context: ./notifications/gateway
      dockerfile: Dockerfile
    container_name: notifications_gateway

    restart: unless-stopped

    environment:
      HTTP_PORT: 8001
      MARKETPLACE_HOST: notifications_primary_server
      MARKETPLACE_PORT: 50052
    
    ports:
      - "8000:8000"
    
    depends_on:
      - notifications_primary_server



volumes:
  marketplace_database_data:
  notifications_database_data: